import createPlayer from '../components/player'
import createShip from '../components/Ship'
import createGameboard from '../components/gameboard'

test('a player should be able to have a board', ()=>{
    const board = createGameboard(10,10)
    const player1 = createPlayer(board)


    expect(player1.getBoard().getCount()).toBe(100)
})

test('a player should be able to attack the enemies board', ()=>{
    const board = createGameboard(10,10)
    const player1 = createPlayer(board)
    const enemiesBoard = createGameboard(10,10)
    const ship1 = createShip(5, 'one')
    enemiesBoard.placeShipHorizontally(ship1,[0,4])

    expect(player1.attack(enemiesBoard,0,6)).toBe(true)
    expect(player1.attack(enemiesBoard,0,3)).toBe(false)
})


test('a computer should make a strike on a valid move and look for other moves when available', ()=>{
    const board = createGameboard(10,10)
    const player1 = createPlayer(board)
    const enemiesBoard = createGameboard(10,10)
    const bot = createPlayer(enemiesBoard)
    const ship1 = createShip(1, 'one')
    const ship3 = createShip(3, 'three')
    
    board.placeShipHorizontally(ship3,[3,3])
    board.placeShipHorizontally(ship3,[5,3])
    board.placeShipHorizontally(ship1,[4,3])
    board.placeShipHorizontally(ship1,[4,5])
    
    expect(bot.computerAttack(4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(true)
    expect(bot.computerAttack(board,4,4)).toBe(false)
    

   
   


  
    console.log(board.getBoard())
    
})



